[zksync]
rpc = "https://mainnet.era.zksync.io"
private_key = "0xb00ba"
fulfiller = false
untron_contract_address = "0x0000000000000000000000000000000000000000"

[tron]
rpc = "https://api.trongrid.io/jsonrpc"
private_key = "0xb00ba"
autocreator = false
min_fee = 2500000