[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
remappings = [
    "@sp1-contracts/=./lib/sp1-contracts/contracts/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "ds-test/=lib/openzeppelin-contracts/lib/forge-std/lib/ds-test/src/",
    "era-contracts/system-contracts/contracts/=lib/v2-testnet-contracts/l2/system-contracts/",
    "era-contracts/l2-contracts/contracts/=lib/v2-testnet-contracts/l2/contracts/",
    "era-contracts/l1-contracts/contracts/=lib/v2-testnet-contracts/l1/contracts/",
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "murky/=lib/era-contracts/l1-contracts/lib/murky/",
    "openzeppelin-contracts-upgradeable/=lib/era-contracts/l1-contracts/lib/openzeppelin-contracts-upgradeable/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
